aws ec2 run-instances \
    --image-id "ami-03074cc1b166e8691" \
    --instance-type "t2.micro" \
    --key-name "test-schluesselpaar" \
    --user-data "IyEvYmluL2Jhc2gKIyBVcGRhdGUgcGFja2FnZSBsaXN0IGFuZCB1cGdyYWRlIGluc3RhbGxlZCBwYWNrYWdlcwp5dW0gdXBkYXRlIC15IAo=" \
    --network-interfaces '{"AssociatePublicIpAddress":true,"DeviceIndex":0,"Groups":["sg-03aa1a77ed6c0835e","sg-059466aabfd4610c3"]}' \
    --credit-specification '{"CpuCredits":"standard"}' \
    --tag-specifications '{"ResourceType":"instance","Tags":[{"Key":"Name","Value":"JobScraper"}]}' \
    --metadata-options '{"HttpEndpoint":"enabled","HttpPutResponseHopLimit":2,"HttpTokens":"required"}' \
    --private-dns-name-options '{"HostnameType":"ip-name","EnableResourceNameDnsARecord":true,"EnableResourceNameDnsAAAARecord":false}' \
    --count "2"
